const map: Record<string,string> = {
 'CONTROL CENTER':'مرکز کنترل','OPERATIONS':'عملیات','MONEY':'مالی','TRUST':'اعتماد و ریسک','SUPPORT':'پشتیبانی','SYSTEM':'سیستم',
 'Overview':'نمای کلی','Users':'کاربران','Sellers':'فروشندگان','Seller Requests':'درخواست فروشندگی','Verification':'احراز هویت','Products':'محصولات','Orders':'سفارش‌ها و معاملات','Finance':'امور مالی','Risk & Trust':'ریسک و اعتماد','Support':'پشتیبانی','Admins & Roles':'ادمین‌ها و دسترسی',
 'POORITEL ADMIN':'ادمین PooriTel','ADMIN COMMAND':'مرکز فرمان','OPEN STORE ↗':'فروشگاه ↗','Today':'امروز','7 days':'۷ روز','30 days':'۳۰ روز',
 'ACTION QUEUE':'صف اقدامات','Needs your decision':'نیازمند تصمیم شما','Review':'بررسی','PLATFORM WALLET':'کیف پول پلتفرم','Platform money':'منابع مالی پلتفرم','Ledger':'دفتر مالی','Available':'موجودی در دسترس','Commission earned':'کمیسیون ثبت‌شده','Pending settlement':'در انتظار تسویه','Refund reserve':'ذخیره بازگشت وجه','Collected today':'دریافت امروز','Seller payouts':'پرداخت فروشندگان','Net commission':'خالص کمیسیون','LIVE':'زنده','Important activity':'فعالیت مهم','FLOW':'گردش مالی','12-day money flow':'گردش مالی ۱۲ روز اخیر','Marketplace health':'سلامت مارکت‌پلیس','Healthy':'سالم','Warning':'هشدار',
 'GMV today':'حجم معاملات امروز','Open orders':'سفارش‌های باز','Seller requests':'درخواست فروشندگی','Pending payouts':'برداشت‌های در انتظار','Seller applications':'درخواست‌های فروشندگی','New product listings':'آگهی‌های جدید محصول','Orders awaiting approval':'معاملات منتظر تأیید','Withdrawal requests':'درخواست برداشت','Identity reviews':'بررسی‌های احراز هویت','wait­ing':'در انتظار',
 'Search users, orders, sellers...':'جستجو در کاربران، سفارش‌ها و فروشندگان...','System nominal':'سیستم عادی','Super Admin':'مدیر ارشد',
 'Seller onboarding':'جذب فروشنده','Product moderation':'تأیید محصول','Order controls':'کنترل معاملات','Payout controls':'کنترل برداشت','Identity & KYC':'احراز هویت و KYC',
 'Moderate and approve seller listings':'مدیریت و تأیید آگهی‌های فروشندگان','Every critical step can be controlled before final settlement':'هر مرحله حساس قبل از نهایی شدن قابل کنترل است','Identity cases requiring admin decision':'پرونده‌های احراز نیازمند تصمیم ادمین','Seller performance and marketplace supply':'عملکرد فروشندگان و عرضه بازار','Customer accounts and activity':'حساب‌ها و فعالیت مشتریان','Production-ready module shell ready for real data':'پوسته ماژول آماده اتصال به داده واقعی',
 'Applicant':'متقاضی','Identity':'احراز هویت','Buyer history':'سابقه خرید','Trust':'اعتماد','Status':'وضعیت','Product':'محصول','Seller':'فروشنده','Price':'قیمت','Category':'دسته','Stage':'مرحله','Reference':'شناسه','Parties':'طرفین','Decision':'تصمیم','Documents':'مدارک','Risk':'ریسک','Item':'مورد','Owner':'مسئول','Priority':'اولویت','Last update':'آخرین بروزرسانی','User':'کاربر','Email':'ایمیل','Orders':'سفارش‌ها','Spend':'هزینه','Type':'نوع',
 'Pending':'در انتظار','Approved':'تأیید شده','Approve':'تأیید','Reject':'رد','Review':'بررسی','Hold':'توقف','Docs review':'بررسی مدارک','Docs missing':'مدارک ناقص','Seller review':'بررسی فروشنده',
 'New seller application':'درخواست فروشندگی جدید','Product submitted':'ثبت محصول جدید','Withdrawal request':'درخواست برداشت','Order approval':'تأیید معامله','Verification update':'بروزرسانی احراز هویت','Payment confirmed':'پرداخت تأیید شد','Delivery received':'تحویل دریافت شد','Refund requested':'درخواست بازگشت وجه','Seller submitted':'ارسال توسط فروشنده','Admin approval':'تأیید ادمین','Complete':'تکمیل شده','Commission':'کمیسیون','Order settlement':'تسویه معامله','Seller balance':'موجودی فروشنده','Refund reserve':'ذخیره بازگشت وجه'
};
let enabled=false;
function walk(root: Node){const w=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);const nodes:Text[]=[];while(w.nextNode())nodes.push(w.currentNode as Text);for(const n of nodes){const raw=n.nodeValue?.trim();if(!raw)continue;if(enabled&&map[raw])n.nodeValue=n.nodeValue!.replace(raw,map[raw]);else if(!enabled){const found=Object.entries(map).find(([,fa])=>fa===raw);if(found)n.nodeValue=n.nodeValue!.replace(raw,found[0]);}}}
export function applyAdminLanguage(fa:boolean){enabled=fa;walk(document.body);document.documentElement.lang=fa?'fa':'en';document.documentElement.dir='ltr';}
new MutationObserver(()=>{if(document.body)walk(document.body)}).observe(document.documentElement,{childList:true,subtree:true});
(window as any).__applyAdminLanguage=applyAdminLanguage;
