import React, { useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';
import './admin-v3.css';
import './admin-v4-fixes.css';
import './admin-v5.css';

type Page = 'overview'|'users'|'sellers'|'requests'|'verification'|'products'|'orders'|'finance'|'risk'|'support'|'admins';
type Lang = 'en'|'fa';

const nav: {id: Page; en: string; fa: string; group: string; icon: string; badge?: string}[] = [
  {id:'overview',en:'Overview',fa:'نمای کلی',group:'CONTROL CENTER',icon:'⌂'},
  {id:'users',en:'Users',fa:'کاربران',group:'OPERATIONS',icon:'◉'},
  {id:'sellers',en:'Sellers',fa:'فروشندگان',group:'OPERATIONS',icon:'◈'},
  {id:'requests',en:'Seller Requests',fa:'درخواست فروشندگی',group:'OPERATIONS',icon:'↗',badge:'17'},
  {id:'verification',en:'Verification',fa:'احراز هویت',group:'OPERATIONS',icon:'✓',badge:'4'},
  {id:'products',en:'Products',fa:'محصولات',group:'OPERATIONS',icon:'▦',badge:'9'},
  {id:'orders',en:'Orders',fa:'سفارش‌ها و معاملات',group:'OPERATIONS',icon:'□',badge:'6'},
  {id:'finance',en:'Finance',fa:'امور مالی',group:'MONEY',icon:'$'},
  {id:'risk',en:'Risk & Trust',fa:'ریسک و اعتماد',group:'TRUST',icon:'⚡',badge:'2'},
  {id:'support',en:'Support',fa:'پشتیبانی',group:'SUPPORT',icon:'?',badge:'5'},
  {id:'admins',en:'Admins & Roles',fa:'ادمین‌ها و دسترسی',group:'SYSTEM',icon:'⚙'},
];

const sellerRequests = [
  {name:'NightFox',email:'fox@example.com',ago:'18m',identity:'Verified',orders:42,spent:'$1,240',trust:96,docs:2,status:'Pending',product:'CS2 DreamHollow',url:'/market/cs2-dreamhollow'},
  {name:'Ariya Games',email:'ariya@example.com',ago:'2h',identity:'Verified',orders:18,spent:'$420',trust:91,docs:2,status:'Pending',product:'Steam Wallet $20',url:'/market/steam-wallet-20'},
  {name:'Mina K',email:'mina@example.com',ago:'5h',identity:'Review',orders:7,spent:'$180',trust:74,docs:1,status:'Docs',product:'Telegram Premium 3M',url:'/market/telegram-premium-3m'},
  {name:'DotaKing',email:'king@example.com',ago:'1d',identity:'Missing',orders:31,spent:'$860',trust:62,docs:0,status:'Hold',product:'Dota 2 Collector Set',url:'/market/dota-collector-set'},
];

const listings = [
  {name:'Steam Wallet $20',seller:'NightFox',price:'$20.00',category:'Steam',stock:'43',url:'/market/steam-wallet-20',submitted:'7m ago',risk:'Low',checks:'Price / category / seller pass'},
  {name:'Telegram Premium 3M',seller:'Ariya Games',price:'$7.99',category:'Subscriptions',stock:'18',url:'/market/telegram-premium-3m',submitted:'21m ago',risk:'Low',checks:'Digital delivery metadata present'},
  {name:'CS2 DreamHollow',seller:'NightFox',price:'$84.50',category:'CS2',stock:'1',url:'/market/cs2-dreamhollow',submitted:'41m ago',risk:'Medium',checks:'Item ownership proof attached'},
  {name:'Dota 2 Collector Set',seller:'Mina K',price:'$14.00',category:'Dota 2',stock:'3',url:'/market/dota-collector-set',submitted:'2h ago',risk:'Medium',checks:'Seller verification review'},
];

const orders = [
  {id:'PT-10492',buyer:'Ali Reza',seller:'NightFox',product:'CS2 DreamHollow',amount:'$84.50',commission:'$8.45',stage:'Payment confirmed',action:'Admin approval',listing:'/market/cs2-dreamhollow',risk:'Low'},
  {id:'PT-10489',buyer:'Nora',seller:'Ariya Games',product:'Steam Wallet $20',amount:'$20.00',commission:'$2.00',stage:'Delivery received',action:'Complete',listing:'/market/steam-wallet-20',risk:'Low'},
  {id:'PT-10481',buyer:'Mika',seller:'Mina K',product:'Telegram Premium 3M',amount:'$7.99',commission:'$0.80',stage:'Refund requested',action:'Review',listing:'/market/telegram-premium-3m',risk:'Medium'},
  {id:'PT-10477',buyer:'Rin',seller:'PixelVault',product:'Dota 2 Set',amount:'$54.00',commission:'$5.40',stage:'Seller submitted',action:'Admin approval',listing:'/market/dota-collector-set',risk:'Low'},
];

const verifications = [
  {user:'Mina K',country:'NL',docs:[{type:'ID / Passport',status:'Missing'}, {type:'Proof of address',status:'Uploaded'}],risk:'Medium',orders:7,trust:74},
  {user:'DotaKing',country:'DE',docs:[{type:'ID / Passport',status:'Missing'}, {type:'Selfie',status:'Missing'}],risk:'High',orders:31,trust:62},
  {user:'NightFox',country:'NL',docs:[{type:'ID / Passport',status:'Verified'}, {type:'Selfie',status:'Verified'}],risk:'Low',orders:42,trust:96},
];

const txns = [
  {ref:'TX-8842',source:'Order PT-10492',amount:'+$8.45',type:'Commission',status:'Settled'},
  {ref:'TX-8841',source:'Order PT-10489',amount:'+$2.00',type:'Commission',status:'Settled'},
  {ref:'TX-8838',source:'Payout #1182',amount:'-$84.50',type:'Seller payout',status:'Pending'},
  {ref:'TX-8835',source:'Refund reserve',amount:'-$32.00',type:'Reserve',status:'Held'},
];

const fa = (lang:Lang, en:string, fa:string) => lang === 'fa' ? fa : en;

function App(){
  const [page,setPage]=useState<Page>('overview');
  const [lang,setLang]=useState<Lang>('en');
  const [dark,setDark]=useState(true);
  const [collapsed,setCollapsed]=useState(false);
  const [mobileOpen,setMobileOpen]=useState(false);
  const [search,setSearch]=useState('');
  const [review,setReview]=useState<{kind:'listing'|'order'|'verification'|'request';index:number}|null>(null);
  const groups=[...new Set(nav.map(n=>n.group))];
  const title = nav.find(n=>n.id===page);
  const go=(p:Page)=>{setPage(p);setMobileOpen(false)};
  return <div className={`admin-v3 ${dark?'dark':''} ${collapsed?'is-collapsed':''}`} dir="ltr">
    <aside className={`sidebar ${collapsed?'collapsed':''} ${mobileOpen?'mobile-open':''}`}>
      <div className="brand"><div className="brand-mark">P</div>{!collapsed&&<div><strong>PooriTel</strong><span>ADMIN COMMAND</span></div>}</div>
      <button className="collapse collapse-fixed" onClick={()=>setCollapsed(v=>!v)} aria-label="Toggle sidebar">{collapsed?'›':'‹'}</button>
      <div className="navScroll">{groups.map(g=><section key={g}><div className="group">{fa(lang,g,groupFa[g]||g)}</div>{nav.filter(n=>n.group===g).map(n=><button key={n.id} className={`nav ${page===n.id?'active':''}`} onClick={()=>go(n.id)} title={lang==='fa'?n.fa:n.en}><i>{n.icon}</i>{!collapsed&&<span>{lang==='fa'?n.fa:n.en}</span>}{!collapsed&&n.badge&&<b>{n.badge}</b>}</button>)}</section>)}</div>
      <div className="sidebar-foot">{!collapsed&&<div className="ops"><span className="dot"/>{fa(lang,'System nominal','سیستم عادی')}</div>}<button className="profile"><span className="avatar">P</span>{!collapsed&&<span className="meta"><strong>Pouria</strong><small>Super Admin</small></span>}</button></div>
    </aside>
    <main className="main">
      <header className="topbar"><button className="mobile-menu" onClick={()=>setMobileOpen(true)}>☰</button><div className="crumb"><span>POORITEL ADMIN</span><b>/</b><strong>{lang==='fa'?(title?.fa||'نمای کلی'):(title?.en||'Overview')}</strong></div><div className="actions"><label className="search">⌕<input value={search} onChange={e=>setSearch(e.target.value)} placeholder={fa(lang,'Search users, orders, sellers...','جستجو در کاربران، سفارش‌ها و فروشندگان...')}/></label><div className="language"><button className={lang==='en'?'active':''} onClick={()=>setLang('en')}>EN</button><button className={lang==='fa'?'active':''} onClick={()=>setLang('fa')}>فا</button></div><button className="tool" onClick={()=>setDark(v=>!v)}>{dark?'☼':'◐'}</button><button className="tool notify">◔<em>3</em></button><button className="store" onClick={()=>window.open('/','_blank')}>{fa(lang,'OPEN STORE ↗','فروشگاه ↗')}</button></div></header>
      <div className="content">
        {page==='overview'&&<Overview lang={lang} go={go} open={setReview}/>} 
        {page==='requests'&&<Requests lang={lang} open={i=>setReview({kind:'request',index:i})}/>} 
        {page==='products'&&<Listings lang={lang} open={i=>setReview({kind:'listing',index:i})}/>} 
        {page==='orders'&&<Orders lang={lang} open={i=>setReview({kind:'order',index:i})}/>} 
        {page==='verification'&&<Verifications lang={lang} open={i=>setReview({kind:'verification',index:i})}/>} 
        {page==='finance'&&<Finance lang={lang}/>} 
        {page==='sellers'&&<TableShell lang={lang} title={fa(lang,'Sellers','فروشندگان')} sub={fa(lang,'Performance, compliance and marketplace supply','عملکرد، احراز و عرضه بازار')} heads={['Seller','GMV 30d','Orders','Completion','Risk']} rows={[["NightFox","$18,420","182","98.4%","Low"],["Ariya Games","$9,840","96","97.1%","Low"],["Mina K","$4,320","54","94.7%","Medium"],["PixelVault","$3,890","48","99.1%","Low"]]}/>} 
        {page==='users'&&<TableShell lang={lang} title={fa(lang,'Users','کاربران')} sub={fa(lang,'Accounts, spend and activity','حساب‌ها، خرید و فعالیت')} heads={['User','Email','Orders','Spend','Status']} rows={[["Ali Reza","ali@example.com","18","$420","Active"],["Nora","nora@example.com","6","$180","Active"],["Mika","mika@example.com","0","$0","New"],["Rin","rin@example.com","22","$860","Review"]]}/>} 
        {page==='risk'&&<TableShell lang={lang} title={fa(lang,'Risk & Trust','ریسک و اعتماد')} sub={fa(lang,'Signals, disputes and watchlist','سیگنال‌ها، اختلاف‌ها و فهرست نظارت')} heads={['Case','Owner','Priority','Last update','Status']} rows={[["Suspicious seller","Trust","High","5 min","2 flagged"],["Payment anomaly","Finance","High","11 min","1 open"],["Dispute queue","Support","Medium","19 min","3 open"],["Watchlist","Security","Low","26 min","Healthy"]]}/>} 
        {page==='support'&&<TableShell lang={lang} title={fa(lang,'Support','پشتیبانی')} sub={fa(lang,'Tickets, escalations and disputes','تیکت‌ها، ارجاع‌ها و اختلاف‌ها')} heads={['Ticket','User','Priority','Order','Status']} rows={[["#T-1824","Ali Reza","High","PT-10492","Open"],["#T-1819","Mina K","Medium","PT-10481","Pending"],["#T-1813","NightFox","Low","—","Resolved"],["#T-1808","Nora","High","PT-10489","Escalated"]]}/>} 
        {page==='admins'&&<TableShell lang={lang} title={fa(lang,'Admins & Roles','ادمین‌ها و دسترسی')} sub={fa(lang,'People, permissions and audit responsibility','کاربران مدیریتی، سطح دسترسی و مسئولیت ثبت رویداد')} heads={['Admin','Role','2FA','Last active','Status']} rows={[["Pouria","Super Admin","Enabled","Now","Active"],["Reza","Finance Admin","Enabled","12 min","Active"],["Sara","Support Admin","Enabled","31 min","Active"],["Nima","Moderator","Enabled","2h","Away"]]}/>} 
      </div>
    </main>
    {mobileOpen&&<button className="backdrop" onClick={()=>setMobileOpen(false)} aria-label="Close menu"/>}
    {review&&<DecisionDrawer lang={lang} review={review} close={()=>setReview(null)}/>} 
  </div>
}

const groupFa:Record<string,string>={"CONTROL CENTER":"مرکز کنترل","OPERATIONS":"عملیات","MONEY":"مالی","TRUST":"اعتماد و ریسک","SUPPORT":"پشتیبانی","SYSTEM":"سیستم"};

function Overview({lang,go,open}:{lang:Lang;go:(p:Page)=>void;open:(r:{kind:'listing'|'order'|'verification'|'request';index:number})=>void}){
 return <div className="stack"><div className="heading"><div><span className="eyebrow">{fa(lang,'OPERATIONS OVERVIEW','مرکز کنترل عملیات')}</span><h1>{fa(lang,'PooriTel today','وضعیت امروز PooriTel')}</h1><p>{fa(lang,'Decisions, exceptions and money movement — prioritized first.','تصمیم‌ها، موارد استثنا و گردش مالی ابتدا در دسترس هستند.')}</p></div><div className="filters"><button className="filter active">{fa(lang,'Today','امروز')}</button><button className="filter">{fa(lang,'7 days','۷ روز')}</button><button className="filter">{fa(lang,'30 days','۳۰ روز')}</button></div></div>
 <div className="kpis">{[[fa(lang,'GMV today','حجم معاملات امروز'),'$12,840','+18.4%','good'],[fa(lang,'Open orders','سفارش‌های باز'),'24',fa(lang,'7 need action','۷ نیازمند اقدام'),'warn'],[fa(lang,'Seller requests','درخواست فروشندگی'),'17',fa(lang,'6 urgent','۶ فوری'),'warn'],[fa(lang,'Pending payouts','برداشت‌های در انتظار'),'$3,420',fa(lang,'11 requests','۱۱ درخواست'),'warn']].map(m=><div className="kpi" key={m[0]}><span>{m[0]}</span><strong>{m[1]}</strong><small className={m[3]}>{m[2]}</small></div>)}</div>
 <div className="opsgrid"><section className="panel"><div className="panelhead"><div><span className="eyebrow">ACTION QUEUE</span><h2>{fa(lang,'Needs your decision','نیازمند تصمیم شما')}</h2></div></div><div className="queue">
 {[["↗",fa(lang,'New seller applications','درخواست‌های فروشندگی جدید'),'17 waiting','requests',0],["▦",fa(lang,'New product listings','آگهی‌های جدید برای تأیید'),'9 pending','products',0],["□",fa(lang,'Orders awaiting approval','معاملات منتظر تأیید'),'6 pending','orders',0],["$",fa(lang,'Withdrawal requests','درخواست‌های برداشت'),'11 pending','finance',0],["✓",fa(lang,'Identity reviews','بررسی‌های احراز هویت'),'4 cases','verification',0]].map((x,i)=><button key={x[1]} onClick={()=>go(x[3] as Page)}><span className="qicon">{x[0]}</span><span><strong>{x[1]}</strong><small>{x[2]}</small></span><em>{fa(lang,'REVIEW','بررسی')}</em></button>)}</div></section>
 <section className="panel"><div className="panelhead"><div><span className="eyebrow">PLATFORM WALLET</span><h2>{fa(lang,'Platform money','منابع مالی پلتفرم')}</h2></div><span className="muted">Ledger</span></div><div className="walletgrid"><div className="walletbox primary"><span>{fa(lang,'Available','موجودی در دسترس')}</span><strong>$8,420.50</strong><small>USD</small></div><div className="walletbox"><span>{fa(lang,'Commission earned','کمیسیون ثبت‌شده')}</span><strong>$1,284.20</strong><small>{fa(lang,'30 days','۳۰ روز')}</small></div><div className="walletbox"><span>{fa(lang,'Pending settlement','در انتظار تسویه')}</span><strong>$3,420</strong><small>11 payouts</small></div><div className="walletbox"><span>{fa(lang,'Refund reserve','ذخیره بازگشت وجه')}</span><strong>$620</strong><small>Reserved</small></div></div><div className="ledger"><div className="ledgerrow"><span>{fa(lang,'Collected today','دریافت امروز')}</span><strong>+$428.50</strong></div><div className="ledgerrow"><span>{fa(lang,'Seller payouts','پرداخت فروشندگان')}</span><strong>-$312.00</strong></div><div className="ledgerrow"><span>{fa(lang,'Net commission','خالص کمیسیون')}</span><strong>+$116.50</strong></div></div></section>
 <section className="panel"><div className="panelhead"><div><span className="eyebrow">LIVE</span><h2>{fa(lang,'Important activity','فعالیت مهم')}</h2></div></div>{[["12:41",fa(lang,'New seller application','درخواست فروشندگی جدید'),'NightFox'],["12:38",fa(lang,'Product submitted','ثبت محصول جدید'),'Steam Wallet $20'],["12:34",fa(lang,'Withdrawal request','درخواست برداشت'),'$84.50'],["12:29",fa(lang,'Order approval','تأیید معامله'),'PT-10492'],["12:21",fa(lang,'Verification update','بروزرسانی احراز هویت'),'Mina K']].map(r=><div className="activityrow" key={r[0]}><time>{r[0]}</time><span><strong>{r[1]}</strong><small>{r[2]}</small></span><i/></div>)}</section></div>
 <div className="lower"><section className="panel"><div className="panelhead"><div><span className="eyebrow">MARKET HEALTH</span><h2>{fa(lang,'Marketplace health','سلامت مارکت‌پلیس')}</h2></div></div><div className="healthline"><span>{fa(lang,'Payments','پرداخت‌ها')}</span><strong className="good">Healthy</strong></div><div className="healthline"><span>{fa(lang,'Verification','احراز هویت')}</span><strong className="warn">4 waiting</strong></div><div className="healthline"><span>{fa(lang,'Payouts','برداشت‌ها')}</span><strong className="warn">11 waiting</strong></div><div className="healthline"><span>{fa(lang,'Risk','ریسک')}</span><strong className="good">Low</strong></div></section></div>
 </div>
}

function Requests({lang,open}:{lang:Lang;open:(i:number)=>void}){return <div className="stack"><div className="heading"><div><span className="eyebrow">SELLER ONBOARDING</span><h1>{fa(lang,'Seller Requests','درخواست‌های فروشندگی')}</h1><p>{fa(lang,'Review identity, buyer history and the first intended listing before approval.','قبل از تأیید، هویت، سابقه خرید و اولین آگهی پیشنهادی را بررسی کنید.')}</p></div><div className="filters"><button className="filter active">17 {fa(lang,'pending','در انتظار')}</button><button className="filter">2 high risk</button><button className="filter">4 {fa(lang,'missing docs','مدرک ناقص')}</button></div></div><section className="tablewrap rich"><table><thead><tr>{['Applicant','Identity','Buyer history','First listing','Trust','Decision'].map(h=><th key={h}>{fa(lang,h,({Applicant:'متقاضی',Identity:'احراز هویت','Buyer history':'سابقه خرید','First listing':'اولین آگهی',Trust:'اعتماد',Decision:'تصمیم'} as any)[h]||h)}</th>)}</tr></thead><tbody>{sellerRequests.map((r,i)=><tr key={r.name}><td><strong>{r.name}</strong><small>{r.email} · {r.ago}</small></td><td><span className={`tag ${r.identity==='Missing'?'red':r.identity==='Review'?'warn':''}`}>{fa(lang,r.identity,r.identity==='Verified'?'تأیید شده':r.identity==='Review'?'بررسی':'ناقص')}</span><small>{r.docs}/2 docs</small></td><td><strong>{r.orders} orders</strong><small>{r.spent} spent</small></td><td><strong>{r.product}</strong><a href={r.url} target="_blank" rel="noreferrer">Preview ↗</a></td><td><strong className="trust-score">{r.trust}</strong><small>/100</small></td><td><button className="reviewbtn" onClick={()=>open(i)}>{fa(lang,'Open review','باز کردن بررسی')}</button></td></tr>)}</tbody></table></section></div>}

function Listings({lang,open}:{lang:Lang;open:(i:number)=>void}){return <div className="stack"><div className="heading"><div><span className="eyebrow">MARKETPLACE MODERATION</span><h1>{fa(lang,'New Listings','آگهی‌های جدید')}</h1><p>{fa(lang,'Every new seller listing can be inspected before it becomes visible to customers.','هر آگهی جدید پیش از نمایش به مشتری باید قابل بررسی باشد.')}</p></div><div className="filters"><button className="filter active">9 {fa(lang,'pending','در انتظار')}</button><button className="filter">3 {fa(lang,'flagged','علامت‌گذاری‌شده')}</button></div></div><section className="listing-grid">{listings.map((r,i)=><article className="listing-card" key={r.name}><div className="thumb"><div className="thumb-orb">P</div><span>{r.category}</span></div><div className="listing-body"><div className="listing-top"><div><span className="eyebrow">LISTING PREVIEW</span><h3>{r.name}</h3><small>{r.seller} · submitted {r.submitted}</small></div><span className={`tag ${r.risk==='Medium'?'warn':''}`}>{r.risk}</span></div><div className="listing-facts"><div><span>Price</span><strong>{r.price}</strong></div><div><span>Stock</span><strong>{r.stock}</strong></div><div><span>Checks</span><strong>Pass</strong></div></div><div className="listing-url"><span>Customer URL</span><a href={r.url} target="_blank" rel="noreferrer">pooritel.app{r.url} ↗</a></div><p className="checkline">✓ {r.checks}</p><button className="inspect" onClick={()=>open(i)}>{fa(lang,'Inspect & decide','مشاهده و تصمیم')}</button></div></article>)}</section></div>}

function Orders({lang,open}:{lang:Lang;open:(i:number)=>void}){return <div className="stack"><div className="heading"><div><span className="eyebrow">TRANSACTION CONTROL</span><h1>{fa(lang,'Orders & Transactions','سفارش‌ها و معاملات')}</h1><p>{fa(lang,'Inspect the listing, money, buyer, seller and exact approval point before settlement.','آگهی، مبلغ، خریدار، فروشنده و نقطه دقیق تأیید را قبل از تسویه بررسی کنید.')}</p></div><div className="filters"><button className="filter active">6 {fa(lang,'need approval','نیازمند تأیید')}</button><button className="filter">3 disputes</button></div></div><section className="tablewrap rich"><table><thead><tr>{['Order','Buyer / Seller','Listing','Amount','Stage','Approval'].map(h=><th key={h}>{fa(lang,h,({Order:'سفارش','Buyer / Seller':'خریدار / فروشنده',Listing:'آگهی',Amount:'مبلغ',Stage:'مرحله',Approval:'تأیید'} as any)[h])}</th>)}</tr></thead><tbody>{orders.map((r,i)=><tr key={r.id}><td><strong>{r.id}</strong><small>{r.risk} risk</small></td><td><strong>{r.buyer}</strong><small>→ {r.seller}</small></td><td><strong>{r.product}</strong><a href={r.listing} target="_blank" rel="noreferrer">Preview ↗</a></td><td><strong>{r.amount}</strong><small>Commission {r.commission}</small></td><td><span className="tag">{r.stage}</span></td><td><button className="reviewbtn" onClick={()=>open(i)}>{r.action}</button></td></tr>)}</tbody></table></section></div>}

function Verifications({lang,open}:{lang:Lang;open:(i:number)=>void}){return <div className="stack"><div className="heading"><div><span className="eyebrow">IDENTITY & COMPLIANCE</span><h1>{fa(lang,'Verification Review','بررسی احراز هویت')}</h1><p>{fa(lang,'Open the actual evidence package before accepting or holding an account.','پیش از تأیید یا توقف حساب، بسته واقعی مدارک و شواهد را بررسی کنید.')}</p></div></div><section className="verification-grid">{verifications.map((r,i)=><article className="verification-card" key={r.user}><div className="v-head"><div><strong>{r.user}</strong><small>{r.country} · {r.orders} orders · Trust {r.trust}</small></div><span className={`tag ${r.risk==='High'?'red':r.risk==='Medium'?'warn':''}`}>{r.risk} risk</span></div><div className="doc-previews">{r.docs.map(d=><div className="doc" key={d.type}><div className={`doc-thumb ${d.status==='Missing'?'missing':''}`}><span>{d.status==='Missing'?'!':'✓'}</span></div><div><strong>{d.type}</strong><small>{d.status}</small></div></div>)}</div><div className="evidence-row"><span>{fa(lang,'Evidence available','مدرک قابل مشاهده')}</span><b>{r.docs.filter(d=>d.status!=='Missing').length}/{r.docs.length}</b></div><button className="inspect" onClick={()=>open(i)}>{fa(lang,'Open evidence & decide','مشاهده مدارک و تصمیم')}</button></article>)}</section></div>}

function Finance({lang}:{lang:Lang}){return <div className="stack"><div className="heading"><div><span className="eyebrow">PLATFORM TREASURY</span><h1>{fa(lang,'Finance','امور مالی')}</h1><p>{fa(lang,'Separate platform funds, commission revenue, reserves and pending seller obligations.','منابع پلتفرم، کمیسیون، ذخایر و تعهدات پرداخت‌نشده فروشندگان جدا دیده می‌شوند.')}</p></div></div><div className="kpis finance-kpis">{[[fa(lang,'Platform available','موجودی پلتفرم'),'$8,420.50'],[fa(lang,'Commission 30d','کمیسیون ۳۰ روز'),'$1,284.20'],[fa(lang,'Pending payouts','برداشت در انتظار'),'$3,420'],[fa(lang,'Refund reserve','ذخیره بازگشت وجه'),'$620']].map(x=><div className="kpi" key={x[0]}><span>{x[0]}</span><strong>{x[1]}</strong><small>USD</small></div>)}</div><section className="tablewrap rich"><table><thead><tr>{['Reference','Source','Amount','Type','Status'].map(h=><th key={h}>{fa(lang,h,({Reference:'شناسه',Source:'منبع',Amount:'مبلغ',Type:'نوع',Status:'وضعیت'} as any)[h])}</th>)}</tr></thead><tbody>{txns.map(r=><tr key={r.ref}><td><strong>{r.ref}</strong></td><td>{r.source}</td><td><strong>{r.amount}</strong></td><td>{r.type}</td><td><span className={`tag ${r.status==='Pending'?'warn':r.status==='Held'?'red':''}`}>{r.status}</span></td></tr>)}</tbody></table></section></div>}

function TableShell({lang,title,sub,heads,rows}:{lang:Lang;title:string;sub:string;heads:string[];rows:string[][]}){return <div className="stack"><div className="heading"><div><span className="eyebrow">OPERATIONS</span><h1>{title}</h1><p>{sub}</p></div></div><section className="tablewrap rich"><table><thead><tr>{heads.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{j===0?<strong>{c}</strong>:c}</td>)}</tr>)}</tbody></table></section></div>}

function DecisionDrawer({lang,review,close}:{lang:Lang;review:{kind:'listing'|'order'|'verification'|'request';index:number};close:()=>void}){
 const data = review.kind==='listing'?listings[review.index]:review.kind==='order'?orders[review.index]:review.kind==='verification'?verifications[review.index]:sellerRequests[review.index];
 return <div className="decision-drawer"><button className="drawer-backdrop" onClick={close} aria-label="Close"/><aside className="drawer-panel"><button className="close" onClick={close}>×</button><span className="eyebrow">{review.kind==='listing'?'LISTING REVIEW':review.kind==='order'?'ORDER REVIEW':review.kind==='verification'?'VERIFICATION CASE':'SELLER APPLICATION'}</span><h2>{review.kind==='listing'?data.name:review.kind==='order'?data.id:review.kind==='verification'?data.user:data.name}</h2><p className="drawer-sub">{review.kind==='listing'?data.seller:review.kind==='order'?`${data.buyer} → ${data.seller}`:review.kind==='verification'?`${data.country} · ${data.orders} orders`:data.email}</p>
 {review.kind==='listing'&&<><div className="preview-board"><div className="preview-media"><div className="preview-orb">P</div></div><div className="preview-copy"><strong>{data.name}</strong><span>{data.category} · {data.stock} available</span><b>{data.price}</b></div></div><div className="detailgrid"><div><span>Customer URL</span><strong>{data.url}</strong></div><div><span>Risk</span><strong>{data.risk}</strong></div><div><span>Seller</span><strong>{data.seller}</strong></div><div><span>Checks</span><strong>Pass</strong></div></div></>}
 {review.kind==='order'&&<><div className="money-card"><span>Customer pays</span><strong>{data.amount}</strong><div><span>Seller</span><b>{data.seller}</b><span>Commission</span><b>{data.commission}</b></div></div><div className="preview-board compact"><div className="preview-media"><div className="preview-orb">P</div></div><div className="preview-copy"><strong>{data.product}</strong><a href={data.listing} target="_blank" rel="noreferrer">Open listing preview ↗</a><span>{data.stage}</span></div></div><div className="detailgrid"><div><span>Approval point</span><strong>{data.action}</strong></div><div><span>Risk</span><strong>{data.risk}</strong></div><div><span>Buyer</span><strong>{data.buyer}</strong></div><div><span>Seller</span><strong>{data.seller}</strong></div></div></>}
 {review.kind==='verification'&&<><div className="identity-banner"><strong>{data.user}</strong><span>{data.country} · Trust {data.trust}/100 · {data.risk} risk</span></div><div className="doc-stack">{data.docs.map(d=><div className="doc-row" key={d.type}><div className={`doc-thumb ${d.status==='Missing'?'missing':''}`}><span>{d.status==='Missing'?'!':'✓'}</span></div><div><strong>{d.type}</strong><small>{d.status}</small></div><button>{d.status==='Missing'?fa(lang,'Request','درخواست'):fa(lang,'View','مشاهده')}</button></div>)}</div><div className="notice">{fa(lang,'Approval must consider document presence, account activity and the risk level together.','تأیید باید هم‌زمان بر اساس مدارک، سابقه حساب و سطح ریسک انجام شود.')}</div></>}
 {review.kind==='request'&&<><div className="identity-banner"><strong>{data.name}</strong><span>{data.email} · Trust {data.trust}/100</span></div><div className="detailgrid"><div><span>Identity</span><strong>{data.identity}</strong></div><div><span>Documents</span><strong>{data.docs}/2</strong></div><div><span>Buyer history</span><strong>{data.orders} orders · {data.spent}</strong></div><div><span>First listing</span><strong>{data.product}</strong></div></div><div className="preview-board compact"><div className="preview-media"><div className="preview-orb">P</div></div><div className="preview-copy"><strong>{data.product}</strong><a href={data.url} target="_blank" rel="noreferrer">Preview intended listing ↗</a><span>Review before seller approval</span></div></div></>}
 <div className="decision"><button className="approve">{fa(lang,'Approve','تأیید')}</button><button>{fa(lang,'Request more information','درخواست اطلاعات بیشتر')}</button><button className="reject">{fa(lang,'Reject / Hold','رد / توقف')}</button></div></aside></div>
}

createRoot(document.getElementById('root')!).render(<App/>);
