import React, {useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';
import './admin-v3.css';

type Page='overview'|'users'|'sellers'|'requests'|'verification'|'products'|'orders'|'finance'|'risk'|'support'|'admins';
const nav:{id:Page;label:string;fa:string;group:string;icon:string}[]=[
 {id:'overview',label:'Overview',fa:'نمای کلی',group:'CONTROL CENTER',icon:'⌂'},
 {id:'users',label:'Users',fa:'کاربران',group:'OPERATIONS',icon:'◉'},
 {id:'sellers',label:'Sellers',fa:'فروشندگان',group:'OPERATIONS',icon:'◈'},
 {id:'requests',label:'Seller Requests',fa:'درخواست فروشندگی',group:'OPERATIONS',icon:'↗'},
 {id:'verification',label:'Verification',fa:'احراز هویت',group:'OPERATIONS',icon:'✓'},
 {id:'products',label:'Products',fa:'محصولات',group:'OPERATIONS',icon:'▦'},
 {id:'orders',label:'Orders',fa:'معاملات و سفارش‌ها',group:'OPERATIONS',icon:'□'},
 {id:'finance',label:'Finance',fa:'امور مالی',group:'MONEY',icon:'$'},
 {id:'risk',label:'Risk & Trust',fa:'ریسک و اعتماد',group:'TRUST',icon:'⚡'},
 {id:'support',label:'Support',fa:'پشتیبانی',group:'SUPPORT',icon:'?'},
 {id:'admins',label:'Admins & Roles',fa:'ادمین‌ها و دسترسی',group:'SYSTEM',icon:'⚙'},
];
const requests=[['Ariya Games','ariya@example.com','2h','Verified','18','91','Seller review'],['Mina K','mina@example.com','5h','Pending','7','74','Docs review'],['NightFox','fox@example.com','1d','Verified','42','96','Seller review'],['DotaKing','king@example.com','2d','Missing','31','62','Docs missing']];
const products=[['Steam Wallet $20','NightFox','$20','Digital','Pending'],['Telegram Premium 3M','Ariya Games','$7.99','Subscription','Pending'],['CS2 Key','PixelVault','$42','Game item','Approved'],['Dota 2 Set','Mina K','$14','Game item','Review']];
const orders=[['PT-10492','Ali → NightFox','$84.50','Payment confirmed','Awaiting admin'],['PT-10489','Nora → Ariya','$129.00','Delivery received','Complete'],['PT-10481','Mika → Mina K','$32.00','Refund requested','Review'],['PT-10477','Rin → PixelVault','$54.00','Seller submitted','Admin approval']];
const tx=[['PT-10492','NightFox','+$84.50','Order settlement','Pending'],['PT-10489','Platform','+$12.90','Commission','Settled'],['PT-10481','Mina K','-$32.00','Refund reserve','Pending'],['PT-10477','PixelVault','+$54.00','Seller balance','Pending']];

const faMap=(page:Page, fa:boolean)=>nav.find(n=>n.id===page)?.[fa?'fa':'label']||'';

function App(){
 const [page,setPage]=useState<Page>('overview'); const [dark,setDark]=useState(true); const [lang,setLang]=useState<'en'|'fa'>('en'); const [collapsed,setCollapsed]=useState(false); const [selected,setSelected]=useState<number|null>(null); const [mobileOpen,setMobileOpen]=useState(false);
 const title=useMemo(()=>lang==='fa'?faMap(page,true):faMap(page,false),[page,lang]);
 const groups=[...new Set(nav.map(n=>n.group))];
 const go=(p:Page)=>{setPage(p);setMobileOpen(false)};
 return <div className={`admin-v3 ${dark?'dark':''}`} dir="ltr">
  <aside className={`sidebar ${collapsed?'collapsed':''} ${mobileOpen?'mobile-open':''}`}>
   <div className="brand"><div className="brand-mark">P</div>{!collapsed&&<div><strong>PooriTel</strong><span>ADMIN COMMAND</span></div>}</div>
   <button className="collapse" onClick={()=>setCollapsed(v=>!v)}>{collapsed?'›':'‹'}</button>
   <div className="navScroll">{groups.map(g=><section key={g}><div className="group">{g}</div>{nav.filter(n=>n.group===g).map(n=><button key={n.id} className={`nav ${page===n.id?'active':''}`} onClick={()=>go(n.id)}><i>{n.icon}</i>{!collapsed&&<span>{lang==='fa'?n.fa:n.label}</span>}{!collapsed&&n.id==='requests'&&<b>17</b>}</button>)}</section>)}</div>
   <div className="sidebar-foot">{!collapsed&&<div className="ops"><span className="dot"/>System nominal</div>}<button className="profile"><span className="avatar">P</span>{!collapsed&&<span className="meta"><strong>Pouria</strong><small>Super Admin</small></span>}</button></div>
  </aside>
  <main className="main">
   <header className="topbar"><button className="mobile-menu" onClick={()=>setMobileOpen(true)}>☰</button><div className="crumb"><span>POORITEL ADMIN</span><b>/</b><strong>{title}</strong></div><div className="actions"><label className="search">⌕<input placeholder={lang==='fa'?'جستجو در کاربران، سفارش‌ها، فروشندگان...':'Search users, orders, sellers...'} /></label><div className="language"><button className={lang==='en'?'active':''} onClick={()=>setLang('en')}>EN</button><button className={lang==='fa'?'active':''} onClick={()=>setLang('fa')}>فا</button></div><button className="tool" onClick={()=>setDark(v=>!v)}>{dark?'☼':'◐'}</button><button className="tool">◔</button><button className="store">OPEN STORE ↗</button></div></header>
   <div className="content">
    {page==='overview'&&<Overview lang={lang} dark={dark} go={go}/>} 
    {page==='requests'&&<Requests lang={lang} selected={selected} setSelected={setSelected}/>} 
    {page==='products'&&<SimpleTable title={lang==='fa'?'محصولات':'Products'} sub={lang==='fa'?'مدیریت و تأیید آگهی‌های فروشندگان':'Moderate and approve seller listings'} heads={lang==='fa'?['محصول','فروشنده','قیمت','دسته','وضعیت']:['Product','Seller','Price','Category','Status']} rows={products}/>} 
    {page==='orders'&&<SimpleTable title={lang==='fa'?'معاملات و سفارش‌ها':'Orders & Transactions'} sub={lang==='fa'?'هر مرحله حساس قبل از نهایی شدن قابل کنترل است':'Every critical step can be controlled before final settlement'} heads={lang==='fa'?['شناسه','طرفین','مبلغ','مرحله','وضعیت']:['Reference','Parties','Amount','Stage','Status']} rows={orders}/>} 
    {page==='finance'&&<Finance lang={lang}/>} 
    {page==='verification'&&<SimpleTable title={lang==='fa'?'احراز هویت':'Verification'} sub={lang==='fa'?'پرونده‌های احراز نیازمند تصمیم ادمین':'Identity cases requiring admin decision'} heads={lang==='fa'?['کاربر','مدرک','خطر','سابقه خرید','تصمیم']:['User','Documents','Risk','Buyer history','Decision']} rows={[["Ariya Games","2/2 complete","Low","18 orders","Approve"],["Mina K","1/2 missing","Medium","7 orders","Review"],["DotaKing","0/2 missing","High","31 orders","Hold"],["NightFox","2/2 complete","Low","42 orders","Approve"]]}/>} 
    {page==='sellers'&&<SimpleTable title={lang==='fa'?'فروشندگان':'Sellers'} sub={lang==='fa'?'عملکرد و سلامت عرضه بازار':'Seller performance and marketplace supply'} heads={['Seller','GMV 30d','Orders','Completion','Risk']} rows={[["NightFox","$18,420","182","98.4%","Low"],["Ariya Games","$9,840","96","97.1%","Low"],["Mina K","$4,320","54","94.7%","Medium"],["PixelVault","$3,890","48","99.1%","Low"]]}/>} 
    {page==='users'&&<SimpleTable title={lang==='fa'?'کاربران':'Users'} sub={lang==='fa'?'حساب‌ها و فعالیت مشتریان':'Customer accounts and activity'} heads={['User','Email','Orders','Spend','Status']} rows={[["Ali Reza","ali@example.com","18","$420","Active"],["Nora","nora@example.com","6","$180","Active"],["Mika","mika@example.com","0","$0","New"],["Rin","rin@example.com","22","$860","Review"]]}/>} 
    {['risk','support','admins'].includes(page)&&<SimpleTable title={title} sub={lang==='fa'?'ماژول عملیاتی آماده اتصال به داده واقعی':'Production-ready module shell ready for real data'} heads={['Item','Owner','Priority','Last update','Status']} rows={[["Dispute queue","Support","High","5 min ago","3 open"],["Risk watchlist","Trust","High","11 min ago","2 flagged"],["Admin approvals","Operations","Medium","19 min ago","8 waiting"],["Audit trail","Security","Low","26 min ago","Healthy"]]}/>}
   </div>
  </main>
  {mobileOpen&&<button className="backdrop" onClick={()=>setMobileOpen(false)} aria-label="Close menu"/>}
 </div>
}

function Overview({lang,go}:{lang:'en'|'fa';dark:boolean;go:(p:Page)=>void}){return <div className="stack"><div className="heading"><div><span className="eyebrow">{lang==='fa'?'مرکز کنترل عملیات':'OPERATIONS OVERVIEW'}</span><h1>{lang==='fa'?'وضعیت امروز PooriTel':'PooriTel today'}</h1><p>{lang==='fa'?'آنچه نیاز به تصمیم یا نظارت دارد، همین‌جا اول نمایش داده می‌شود.':'Decisions, exceptions and money movement — prioritized first.'}</p></div><div className="filters"><button className="filter active">Today</button><button className="filter">7 days</button><button className="filter">30 days</button></div></div>
 <div className="kpis">{[[lang==='fa'?'حجم معاملات امروز':'GMV today','$12,840','+18.4%','good'],[lang==='fa'?'سفارش‌های باز':'Open orders','24','7 need action','warn'],[lang==='fa'?'درخواست فروشندگی':'Seller requests','17','6 urgent','warn'],[lang==='fa'?'برداشت‌های در انتظار':'Pending payouts','$3,420','11 requests','warn']].map((m)=><div className="kpi" key={m[0]}><span>{m[0]}</span><strong>{m[1]}</strong><small className={m[3]}>{m[2]}</small></div>)}</div>
 <div className="opsgrid"><section className="panel"><div className="panelhead"><div><span className="eyebrow">ACTION QUEUE</span><h2>{lang==='fa'?'اول این‌ها را بررسی کن':'Needs your decision'}</h2></div></div><div className="queue">{[["↗",lang==='fa'?'درخواست فروشندگی جدید':'Seller applications','17 waiting','requests'],["▦",lang==='fa'?'آگهی‌های جدید برای تأیید':'New product listings','9 pending','products'],["□",lang==='fa'?'معاملات منتظر تأیید':'Orders awaiting approval','6 pending','orders'],["$",lang==='fa'?'برداشت‌های پولی':'Withdrawal requests','11 pending','finance'],["✓",lang==='fa'?'احراز هویت‌های منتظر':'Identity reviews','4 cases','verification']].map(x=><button key={x[1]} onClick={()=>go(x[3] as Page)}><span className="qicon">{x[0]}</span><span><strong>{x[1]}</strong><small>{x[2]}</small></span><em>Review</em></button>)}</div></section>
 <section className="panel"><div className="panelhead"><div><span className="eyebrow">PLATFORM WALLET</span><h2>{lang==='fa'?'کیف پول پلتفرم':'Platform money'}</h2></div><span className="muted">Ledger</span></div><div className="walletgrid"><div className="walletbox primary"><span>{lang==='fa'?'موجودی در دسترس':'Available'}</span><strong>$8,420.50</strong><small>USD</small></div><div className="walletbox"><span>{lang==='fa'?'کمیسیون ثبت شده':'Commission earned'}</span><strong>$1,284.20</strong><small>30d</small></div><div className="walletbox"><span>{lang==='fa'?'در انتظار تسویه':'Pending settlement'}</span><strong>$3,420</strong><small>11 payouts</small></div><div className="walletbox"><span>{lang==='fa'?'ذخیره بازگشت وجه':'Refund reserve'}</span><strong>$620</strong><small>Reserved</small></div></div><div className="ledger"><div className="ledgerrow"><span>{lang==='fa'?'امروز دریافت شده':'Collected today'}</span><strong>+$428.50</strong></div><div className="ledgerrow"><span>{lang==='fa'?'پرداخت به فروشنده':'Seller payouts'}</span><strong>-$312.00</strong></div><div className="ledgerrow"><span>{lang==='fa'?'خالص کمیسیون':'Net commission'}</span><strong>+$116.50</strong></div></div></section>
 <section className="panel"><div className="panelhead"><div><span className="eyebrow">LIVE</span><h2>{lang==='fa'?'فعالیت مهم':'Important activity'}</h2></div></div>{[["12:41","Seller application","NightFox"],["12:38","Product submitted","Steam Wallet $20"],["12:34","Withdrawal request","$84.50"],["12:29","Order approval","PT-10492"],["12:21","Verification update","Mina K"]].map(r=><div className="activityrow" key={r[0]}><time>{r[0]}</time><span><strong>{r[1]}</strong><small>{r[2]}</small></span><i/></div>)}</section></div>
 <div className="lower"><section className="panel"><div className="panelhead"><div><span className="eyebrow">FLOW</span><h2>{lang==='fa'?'گردش مالی ۱۲ روز اخیر':'12-day money flow'}</h2></div><span className="muted">USD</span></div><div className="bar">{[38,48,42,64,58,72,62,82,70,93,77,88].map((h,i)=><i style={{height:`${h}%`}} key={i}/>)}</div></section><section className="panel"><div className="panelhead"><div><span className="eyebrow">HEALTH</span><h2>{lang==='fa'?'وضعیت سرویس':'Marketplace health'}</h2></div></div>{[["Payments","Operational","good"],["Verification","4 pending","warn"],["Payouts","11 pending","warn"],["Orders","24 open","good"],["Risk engine","2 flagged","warn"]].map(r=><div className="healthline" key={r[0]}><span>{r[0]}</span><strong className={r[2]}>{r[1]}</strong></div>)}</section></div>
 </div>}

function Requests({lang,selected,setSelected}:{lang:'en'|'fa';selected:number|null;setSelected:(n:number|null)=>void}){return <div className="stack"><div className="heading"><div><span className="eyebrow">SELLER ONBOARDING</span><h1>{lang==='fa'?'درخواست‌های فروشندگی':'Seller Requests'}</h1><p>{lang==='fa'?'قبل از فعال‌سازی، حساب، احراز، سابقه خرید و ریسک را کنار هم ببین.':'Review identity, buyer history and risk before activation.'}</p></div><div className="filters"><button className="filter active">Pending 17</button><button className="filter">High risk 2</button><button className="filter">Missing docs 4</button></div></div><div className="tablewrap"><table><thead><tr><th>Applicant</th><th>Identity</th><th>Buyer history</th><th>Trust</th><th>Decision</th></tr></thead><tbody>{requests.map((r,i)=><tr key={r[0]} onClick={()=>setSelected(i)} style={{cursor:'pointer'}}><td><strong>{r[0]}</strong><small>{r[1]} · {r[2]}</small></td><td><span className={`tag ${r[3]==='Missing'?'red':r[3]==='Pending'?'warn':''}`}>{r[3]}</span></td><td>{r[4]} orders</td><td><strong>{r[5]}/100</strong></td><td><span className="tag warn">{r[6]}</span></td></tr>)}</tbody></table></div>{selected!==null&&<div className="drawer"><div className="backdrop" onClick={()=>setSelected(null)}/><div className="drawerpanel"><button className="close" onClick={()=>setSelected(null)}>×</button><span className="eyebrow">APPLICATION #{10482+selected}</span><h2>{requests[selected][0]}</h2><p className="muted">{requests[selected][1]}</p><div className="decisionscore"><div><small>TRUST SCORE</small><strong>{requests[selected][5]}</strong><span>/100</span></div><span className="tag warn">{requests[selected][6]}</span></div><div className="detailgrid"><div><span>IDENTITY</span><strong>{requests[selected][3]}</strong></div><div><span>BUYER ORDERS</span><strong>{requests[selected][4]}</strong></div><div><span>ACCOUNT AGE</span><strong>84 days</strong></div><div><span>DISPUTES</span><strong>0</strong></div></div><div className="checks"><p>✓ Email verified</p><p>✓ Phone verified</p><p>✓ Account active</p><p>{requests[selected][3]==='Missing'?'! Identity document missing':'✓ Identity document present'}</p></div><div className="decision"><button className="approve">Approve seller</button><button>Request more info</button><button className="reject">Reject application</button></div></div></div>}</div>}

function SimpleTable({title,sub,heads,rows}:{title:string;sub:string;heads:string[];rows:string[][]}){return <div className="stack"><div className="heading"><div><span className="eyebrow">MODULE</span><h1>{title}</h1><p>{sub}</p></div></div><div className="tablewrap"><table><thead><tr>{heads.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{j===0?<strong>{c}</strong>:<span className={c.toLowerCase().includes('pending')||c.toLowerCase().includes('review')||c.toLowerCase().includes('hold')?'tag warn':'tag'}>{c}</span>}</td>)}</tr>)}</tbody></table></div></div>}

function Finance({lang}:{lang:'en'|'fa'}){return <div className="stack"><div className="heading"><div><span className="eyebrow">MONEY CONTROL</span><h1>{lang==='fa'?'مالی و تسویه':'Finance'}</h1><p>{lang==='fa'?'پول پلتفرم، کمیسیون، برداشت‌ها و بازگشت وجه در یک نمای قابل ردیابی.':'Platform wallet, commissions, payouts and refunds in one traceable view.'}</p></div></div><div className="kpis"><div className="kpi"><span>Platform wallet</span><strong>$8,420</strong><small className="good">Available</small></div><div className="kpi"><span>Commission 30d</span><strong>$1,284</strong><small className="good">+14.2%</small></div><div className="kpi"><span>Pending payouts</span><strong>$3,420</strong><small className="warn">11 waiting</small></div><div className="kpi"><span>Refund reserve</span><strong>$620</strong><small className="warn">4 cases</small></div></div><div className="tablewrap"><table><thead><tr><th>Reference</th><th>Account</th><th>Amount</th><th>Type</th><th>Status</th></tr></thead><tbody>{tx.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{j===0?<strong>{c}</strong>:<span className={c==='Pending'?'tag warn':'tag'}>{c}</span>}</td>)}</tr>)}</tbody></table></div></div>}

createRoot(document.getElementById('root')!).render(<App/>);
