import React, {useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';

type Page='overview'|'users'|'sellers'|'requests'|'verification'|'products'|'orders'|'finance'|'risk'|'support'|'admins';
const nav:{id:Page;label:string;group:string;icon:string}[]=[
{id:'overview',label:'Overview',group:'CONTROL CENTER',icon:'⌂'},
{id:'users',label:'Users',group:'OPERATIONS',icon:'◉'},{id:'sellers',label:'Sellers',group:'OPERATIONS',icon:'◈'},{id:'requests',label:'Seller Requests',group:'OPERATIONS',icon:'↗'},{id:'verification',label:'Verification',group:'OPERATIONS',icon:'✓'},{id:'products',label:'Products',group:'OPERATIONS',icon:'▦'},{id:'orders',label:'Orders',group:'OPERATIONS',icon:'□'},
{id:'finance',label:'Finance',group:'MONEY',icon:'$'},{id:'risk',label:'Risk & Trust',group:'TRUST',icon:'⚡'},{id:'support',label:'Support',group:'SUPPORT',icon:'?'},{id:'admins',label:'Admins & Roles',group:'SYSTEM',icon:'⚙'},
];
const requests=[['Ariya Games','ariya@example.com','2h ago','Verified','18','91','Pending'],['Mina K','mina@example.com','5h ago','Pending','7','74','Review'],['NightFox','fox@example.com','1d ago','Verified','42','96','Pending'],['DotaKing','king@example.com','2d ago','Missing','31','62','Docs']];
const sellers=[['NightFox','$18,420','182','98.4%','Low'],['Ariya Games','$9,840','96','97.1%','Low'],['Mina K','$4,320','54','94.7%','Medium'],['PixelVault','$3,890','48','99.1%','Low']];
const money=[['PT-10492','NightFox','+$84.50','Payout','Pending'],['PT-10489','Ariya Games','+$129.00','Sale','Completed'],['PT-10481','Mina K','-$32.00','Refund','Completed'],['PT-10477','PixelVault','+$54.00','Sale','Completed']];

function App(){
 const [page,setPage]=useState<Page>('overview'); const [collapsed,setCollapsed]=useState(false); const [dark,setDark]=useState(true); const [query,setQuery]=useState(''); const [selected,setSelected]=useState<number|null>(null);
 const title=useMemo(()=>nav.find(n=>n.id===page)?.label||'Overview',[page]);
 const groups=[...new Set(nav.map(n=>n.group))];
 const filtered=sellers.filter(r=>r.join(' ').toLowerCase().includes(query.toLowerCase()));
 return <div className={dark?'admin dark':'admin light'}>
   <aside className={collapsed?'sidebar collapsed':'sidebar'}>
    <div className="brand"><div className="brand-mark">P</div>{!collapsed&&<div><strong>PooriTel</strong><span>ADMIN COMMAND</span></div>}</div>
    <button className="collapse" onClick={()=>setCollapsed(v=>!v)}>{collapsed?'›':'‹'}</button>
    <div className="navScroll">{groups.map(g=><section key={g}><div className="group">{collapsed?'':g}</div>{nav.filter(n=>n.group===g).map(n=><button className={page===n.id?'nav active':'nav'} key={n.id} onClick={()=>setPage(n.id)} title={n.label}><i>{n.icon}</i>{!collapsed&&<span>{n.label}</span>}{!collapsed&&n.id==='requests'&&<b>17</b>}</button>)}</section>)}</div>
    <div className="sidebar-foot">{!collapsed&&<div className="ops"><span className="dot"/>System nominal</div>}<button className="profile"><span className="avatar">P</span>{!collapsed&&<span><strong>Pouria</strong><small>Super Admin</small></span>}</button></div>
   </aside>
   <main className="main">
    <header className="topbar"><div className="crumb"><span>POORITEL ADMIN</span><b>/</b><strong>{title}</strong></div><div className="top-actions"><label className="search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search users, orders, sellers..."/></label><button className="topbtn" onClick={()=>setDark(v=>!v)}>{dark?'☼':'◐'}</button><button className="topbtn">◔<em>3</em></button><button className="store">OPEN STORE ↗</button></div></header>
    <div className="content">
      {page==='overview'&&<Overview setPage={setPage}/>} 
      {page==='requests'&&<Requests selected={selected} setSelected={setSelected}/>} 
      {page==='sellers'&&<TablePage title="Sellers" subtitle="Performance and marketplace health" rows={filtered} head={['Seller','GMV 30d','Orders','Completion','Risk']}/>} 
      {page==='users'&&<TablePage title="Users" subtitle="Customer accounts and activity" rows={[["Ali Reza","ali@example.com","18 orders","$420 spent","Active"],["Nora","nora@example.com","6 orders","$180 spent","Active"],["Mika","mika@example.com","0 orders","$0 spent","New"],["Rin","rin@example.com","22 orders","$860 spent","Review"]]} />}
      {page==='finance'&&<TablePage title="Finance" subtitle="Wallets, transactions and payouts" rows={money} head={['Reference','Account','Amount','Type','Status']}/>} 
      {['verification','products','orders','risk','support','admins'].includes(page)&&<Placeholder page={page}/>} 
    </div>
   </main>
 </div>
}
function Overview({setPage}:{setPage:(p:Page)=>void}){return <div className="stack">
 <div className="hero-line"><div><span className="eyebrow">LIVE CONTROL CENTER</span><h1>Good evening, Pouria.</h1><p>Here’s what needs attention across PooriTel today.</p></div><div className="live-orbit"><div className="ring r1"/><div className="ring r2"/><div className="orb o1"/><div className="orb o2"/><div className="orb o3"/><strong>LIVE</strong></div></div>
 <div className="metrics">{[['GMV Today','$12,840','+18.4%'],['Orders Today','184','+12.1%'],['Seller Requests','17','6 urgent'],['Payout Queue','$3,420','11 pending']].map((m,i)=><div className="metric" key={m[0]}><span>{m[0]}</span><strong>{m[1]}</strong><b className={i===2?'warn':''}>{m[2]}</b><div className="spark"><i/><i/><i/><i/><i/><i/></div></div>)}</div>
 <div className="grid2"><section className="panel attention"><div className="panel-head"><div><span className="eyebrow">NEEDS ATTENTION</span><h2>Priority queue</h2></div><button onClick={()=>setPage('requests')}>View all</button></div>{[['Seller applications','17 pending','requests','requests'],['Verification issues','4 accounts','verification','verification'],['Disputes','3 open cases','risk','risk'],['Payouts','11 waiting','finance','finance']].map((x,i)=><button key={x[0]} className="priority" onClick={()=>setPage(x[2] as Page)}><span className="priority-icon">{['↗','✓','⚡','$'][i]}</span><span><strong>{x[0]}</strong><small>{x[1]}</small></span><b>›</b></button>)}</section><section className="panel feed"><div className="panel-head"><div><span className="eyebrow">LIVE ACTIVITY</span><h2>What’s happening</h2></div><span className="live-tag">● LIVE</span></div>{[['12:41','New seller application','NightFox'],['12:38','Order completed','PT-10492'],['12:34','Payout requested','$84.50'],['12:29','Dispute opened','PT-10477'],['12:21','Product approved','Steam Wallet · $20']].map(r=><div className="feed-row" key={r[0]}><time>{r[0]}</time><span><strong>{r[1]}</strong><small>{r[2]}</small></span><i/></div>)}</section></div>
 <section className="panel snapshot"><div className="panel-head"><div><span className="eyebrow">MARKETPLACE SNAPSHOT</span><h2>One glance overview</h2></div><button>Open analytics →</button></div><div className="snapshot-grid"><div className="chart"><div className="chart-top"><span>Revenue</span><strong>$38.2k</strong></div><div className="bars">{[42,62,54,74,58,83,67,92,78,96,84,100].map((h,i)=><i style={{height:`${h}%`}} key={i}/>)}</div></div><div className="donut"><div className="donut-ring"><span>184</span><small>orders</small></div><div><p><i className="key teal"/>Completed <b>72%</b></p><p><i className="key amber"/>Processing <b>18%</b></p><p><i className="key gray"/>Other <b>10%</b></p></div></div><div className="mini-stack"><div><span>Active sellers</span><strong>248</strong></div><div><span>Conversion</span><strong>4.8%</strong></div><div><span>Refund rate</span><strong>1.2%</strong></div></div></div></section>
 </div>}
function Requests({selected,setSelected}:{selected:number|null;setSelected:(n:number|null)=>void}){return <div className="stack"><div className="page-head"><div><span className="eyebrow">OPERATIONS / SELLER ONBOARDING</span><h1>Seller Requests</h1><p>Review applicants before they enter the marketplace.</p></div><div className="filters"><button className="filter active">Pending <b>17</b></button><button className="filter">High risk <b>2</b></button><button className="filter">Missing docs <b>4</b></button></div></div><section className="panel table-panel"><div className="table-head"><span>Applicant</span><span>Identity</span><span>Buyer history</span><span>Trust</span><span>Status</span></div>{requests.map((r,i)=><button className="table-row" key={r[0]} onClick={()=>setSelected(i)}><span><strong>{r[0]}</strong><small>{r[1]}</small></span><span><b className={r[3]==='Verified'?'good':r[3]==='Missing'?'danger':''}>{r[3]}</b></span><span>{r[4]} orders</span><span><b className="score">{r[5]}</b>/100</span><span><b className="pill">{r[6]}</b></span></button>)} </section>{selected!==null&&<div className="drawer"><div className="drawer-backdrop" onClick={()=>setSelected(null)}/><div className="detail"><button className="close" onClick={()=>setSelected(null)}>×</button><span className="eyebrow">APPLICATION #{10482+selected}</span><h2>{requests[selected][0]}</h2><p>{requests[selected][1]}</p><div className="decision-score"><div><small>TRUST SCORE</small><strong>{requests[selected][5]}</strong><span>/100</span></div><b>{requests[selected][6]}</b></div><div className="detail-grid"><div><small>IDENTITY</small><strong>{requests[selected][3]}</strong></div><div><small>BUYER ORDERS</small><strong>{requests[selected][4]}</strong></div><div><small>ACCOUNT AGE</small><strong>84 days</strong></div><div><small>DISPUTES</small><strong>0</strong></div></div><div className="checks"><p>✓ Email verified</p><p>✓ Phone verified</p><p>✓ Account in good standing</p><p className={requests[selected][3]==='Missing'?'bad':''}>{requests[selected][3]==='Missing'?'! Identity document required':'✓ Identity document present'}</p></div><div className="decision"><button className="approve">Approve seller</button><button>Request more info</button><button className="reject">Reject application</button></div></div></div>}</div>}
function TablePage({title,subtitle,rows,head=['Name','Detail 1','Detail 2','Detail 3','Status']}:{title:string;subtitle:string;rows:string[][];head?:string[]}){return <div className="stack"><div className="page-head"><div><span className="eyebrow">OPERATIONS</span><h1>{title}</h1><p>{subtitle}</p></div><button className="primary">＋ Create</button></div><section className="panel table-panel"><div className="table-head">{head.map(h=><span key={h}>{h}</span>)}</div>{rows.map((r,i)=><div className="table-row static" key={i}>{r.map((c,j)=><span key={j}>{j===0?<strong>{c}</strong>:c}</span>)}</div>)}</section></div>}
function Placeholder({page}:{page:string}){return <div className="placeholder panel"><div className="placeholder-art"><div className="scanline"/></div><span className="eyebrow">MODULE READY</span><h1>{page.charAt(0).toUpperCase()+page.slice(1)}</h1><p>This preview reserves the complete navigation and information architecture. The production module will plug into the same command center shell.</p></div>}

createRoot(document.getElementById('root')!).render(<App/>);
