import React,{useState}from'react';import{createRoot}from'react-dom/client';import'./styles.css';
type Page='overview'|'users'|'sellers'|'requests'|'listings'|'orders'|'wallet'|'payouts'|'verification'|'disputes'|'risk'|'support'|'admins'|'audit'|'settings';type Lang='fa'|'en';
const nav:[string,string,Page,string][]=[['نمای کلی','Overview','overview','⌂'],['کاربران','Users','users','◉'],['فروشندگان','Sellers','sellers','◈'],['درخواست فروشندگی','Seller Requests','requests','↗'],['آگهی‌ها','Listings','listings','▦'],['سفارش‌ها و معاملات','Orders & Trades','orders','□'],['کیف پول پلتفرم','Platform Wallet','wallet','◒'],['برداشت‌ها','Payouts','payouts','$'],['احراز هویت','Verification / KYC','verification','✓'],['اختلاف و بازگشت وجه','Disputes & Refunds','disputes','↺'],['ریسک و اعتماد','Risk & Trust','risk','⚡'],['پشتیبانی و تیکت‌ها','Support & Tickets','support','?'],['ادمین‌ها و دسترسی','Admins & Roles','admins','⚙'],['ثبت رویداد','Audit Log','audit','≋'],['تنظیمات سیستم','System Settings','settings','◌']];
const actions=[['درخواست فروشندگی','17','cyan','requests'],['آگهی منتظر تأیید','9','violet','listings'],['معامله منتظر تأیید','6','amber','orders'],['برداشت منتظر بررسی','11','mint','payouts'],['احراز هویت','4','rose','verification']];
function Core(){return <div className="living-core" aria-hidden="true"><div className="core-halo h1"/><div className="core-halo h2"/><div className="core-halo h3"/><div className="core-shard s1"/><div className="core-shard s2"/><div className="core-shard s3"/><div className="core-surface"/></div>}
function App(){const[page,setPage]=useState<Page>('overview');const[lang,setLang]=useState<Lang>('fa');const[dark,setDark]=useState(false);const[collapsed,setCollapsed]=useState(false);const[modal,setModal]=useState<string|null>(null);const fa=lang==='fa';const title=nav.find(n=>n[2]===page)?.[0];const open=(p:Page)=>setPage(p);return <div className={`app ${dark?'dark':''} ${collapsed?'collapsed':''}`}>
{page==='overview'&&<div className="back-core"><Core/></div>}
<header className="topbar glass"><div className="brand"><span className="logo">P</span><div><strong>PooriTel</strong></div></div><div className="top-center"><span className="live-dot"/>{fa?'سیستم پایدار':'SYSTEM NOMINAL'}<span>·</span>{fa?'عملیات زنده':'LIVE OPS'}</div><div className="top-actions"><button className="glass-btn" onClick={()=>setLang(fa?'en':'fa')}>{fa?'EN':'فا'}</button><button className="glass-btn" onClick={()=>setDark(v=>!v)}>{dark?'☀':'◐'}</button><button className="store">{fa?'فروشگاه ↗':'Open Store ↗'}</button></div></header>
<aside className="sidebar glass"><button className="toggle" onClick={()=>setCollapsed(v=>!v)}>{collapsed?'›':'‹'}</button><div className="nav-top">{fa?'کنترل سیستم':'SYSTEM CONTROL'}</div><div className="nav">{nav.map(([f,e,id,ic])=><button key={id} className={page===id?'active':''} onClick={()=>open(id)}><i>{ic}</i><span>{fa?f:e}</span>{['requests','listings','orders','payouts','verification','support'].includes(id)&&<b>{id==='requests'?'17':id==='listings'?'9':id==='orders'?'6':id==='payouts'?'11':id==='verification'?'4':'5'}</b>}</button>)}</div><div className="profile"><div className="avatar">P</div><div><strong>Pouria</strong><small>{fa?'مدیر ارشد':'Super Admin'}</small></div></div></aside>
<main className="content"><div className="pagehead"><div><h1>{fa?(title||'نمای کلی'):(nav.find(n=>n[2]===page)?.[1]||'Overview')}</h1></div><div className="head-actions"><button className="glass-btn">⌘ K</button><button className="glass-btn">{fa?'اعلان‌ها':'Alerts'} <em>3</em></button></div></div>
{page==='overview'?<Overview fa={fa} open={setModal}/>:<Placeholder fa={fa} page={page} open={setModal}/>}</main>
{modal&&<div className="modal" onMouseDown={()=>setModal(null)}><div className="modal-card glass" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={()=>setModal(null)}>×</button><span className="eyebrow">{fa?'فضای تصمیم':'DECISION WORKSPACE'}</span><h2>{fa?'جزئیات بررسی':'Review details'}</h2><div className="evidence"><div><span>{fa?'حساب':'ACCOUNT'}</span><b>NightFox</b></div><div><span>{fa?'ریسک':'RISK'}</span><b>LOW</b></div><div><span>{fa?'مدرک':'EVIDENCE'}</span><b>{fa?'آماده':'Ready'}</b></div><div><span>{fa?'زمان':'UPDATED'}</span><b>12:41</b></div></div><div className="preview"><div className="mini-core"><span>P</span></div><div><b>{fa?'پیش‌نمایش مورد':'Item preview'}</b><p>{fa?'تمام اطلاعات لازم برای تصمیم در این پنجره جمع شده است.':'All decision-critical context is assembled here.'}</p></div></div><div className="modal-actions"><button>{fa?'نگه‌داشتن':'Hold'}</button><button className="danger">{fa?'رد':'Reject'}</button><button className="primary">{fa?'تأیید':'Approve'} ✓</button></div></div></div>}
</div>}
function Overview({fa,open}:{fa:boolean;open:(x:string)=>void}){return <><section className="minimal-overview"><div className="overview-void"/><section className="action-ribbon glass"><div className="ribbon-title"><span className="eyebrow">{fa?'نیازمند اقدام':'ACTION QUEUE'}</span><strong>{fa?'47 مورد باز':'47 OPEN'}</strong></div>{actions.map(([f,e,t,p])=><button key={p} className={`action-node ${t}`} onClick={()=>open(p)}><span className="node-count">{fa?f:e}</span><small>{fa?f:e}</small><b>{fa?'بررسی':'Review'} →</b></button>)}</section><section className="lower"><div className="panel glass"><div className="panel-head"><span className="eyebrow">PLATFORM MONEY</span><strong>{fa?'مغز مالی':'Money Core'}</strong></div><div className="money-core"><div className="money-ring"><span>$8.4K</span><small>{fa?'موجودی':'AVAILABLE'}</small></div><div className="money-list"><div><span>{fa?'کمیسیون':'Commission'}</span><b>$1,284</b></div><div><span>{fa?'تسویه معلق':'Pending settlement'}</span><b>$3,420</b></div><div><span>{fa?'ذخیره بازگشت':'Refund reserve'}</span><b>$620</b></div></div></div></div><div className="panel glass"><div className="panel-head"><span className="eyebrow">TRUST</span><strong>{fa?'میدان اعتماد':'Trust Field'}</strong></div><div className="trust-score"><b>94.7</b><span>{fa?'ایمن':'SAFE'}</span></div><div className="trust-bar"><i/></div><div className="trust-marks"><span>{fa?'ریسک فروشنده':'Seller risk'} 1.8%</span><span>{fa?'اختلاف':'Disputes'} 0.7%</span><span>KYC 96%</span></div></div><div className="panel glass signal-panel"><div className="panel-head"><span className="eyebrow">LIVE SIGNALS</span><strong>{fa?'جریان فعالیت':'Signal Stream'}</strong></div><div className="wave">{Array.from({length:18}).map((_,i)=><i key={i} style={{height:`${20+((i*17)%70)}%`}}/>)}</div><div className="signal-row"><b>12:41</b><span>{fa?'آگهی جدید ثبت شد':'Listing submitted'}</span><em>NightFox</em></div><div className="signal-row"><b>12:38</b><span>{fa?'درخواست برداشت':'Payout requested'}</span><em>$84.50</em></div></div></section></section></>}
function Placeholder({fa,page,open}:{fa:boolean;page:Page;open:(x:string)=>void}){const label=nav.find(n=>n[2]===page);return <section className="placeholder glass"><div><h2>{fa?label?.[0]:label?.[1]}</h2><button className="primary" onClick={()=>open(page)}>{fa?'باز کردن فضای تصمیم':'Open Decision Workspace'} →</button></div></section>}
createRoot(document.getElementById('root')!).render(<App/>);
