import React from 'react';import{AnimatePresence,motion}from'framer-motion';import type{Currency,JourneyItem,Lang,Theme,Ticket}from'../types';
const products=[['Telegram Premium · 12 Months','تلگرام پریمیوم · ۱۲ ماهه','$21.90'],['Steam Wallet · $20','استیم والت · ۲۰ دلار','$20.00'],['Dota 2 · Immortal Bundle','دوتا ۲ · باندل ایمورتال','$34.50'],['Spotify Premium · 3 Months','اسپاتیفای پریمیوم · ۳ ماهه','$14.99']];
export function Sidebar(p:any){const fa=p.lang==='fa',items=[[p.t.navHub,'hub','⌂'],[p.t.navWallet,'wallet','◈'],[p.t.navOrders,'orders','◫'],[p.t.navProfile,'profile','◉'],[p.t.navSecurity,'security','◒'],[p.t.navSettings,'settings','⚙'],[p.t.navSupport,'support','?']];return <aside className={'v1-side '+(p.collapsed?'collapsed':'')+(p.mobOpen?' mobile-open':'')}><div className="v1-brand"><b>PooriTel</b><small>Customer Space</small></div><button onClick={p.onCollapse}>☰</button>{items.map(([l,k,i])=><button key={String(k)} className={p.active===k?'on':''} onClick={()=>p.onNav(k,k==='hub'?'nowSec':k==='wallet'?'walletSec':k==='orders'?'nowSec':k==='support'?'supportSec':undefined)}><span>{i}</span>{!p.collapsed&&<label>{l}</label>}</button>)}<div className="v1-side-bottom"><div className="v1-seg"><button onClick={()=>p.onLang('en')}>EN</button><button onClick={()=>p.onLang('fa')}>FA</button></div><button onClick={p.onTheme}>{p.theme==='dark'?'☼':'☾'} {!p.collapsed&&(p.theme==='dark'?'Light':'Dark')}</button><div className="v1-user"><b>Pouria</b><small>pouria@mail.com</small></div></div></aside>}
export function TopBar(p:any){return <header className="v1-top"><div><b>{p.t.scenery}</b><small>· {p.t.user}</small></div><input value={p.q} onChange={e=>p.onQ(e.target.value)} placeholder={p.t.searchPh}/><button onClick={p.onTheme}>{p.theme==='dark'?'☼':'☾'}</button><button onClick={p.onMenu}>☰</button></header>}
export function NowSignal(p:any){const fa=p.lang==='fa';if(p.scenario==='clear')return <div className="v1-now"><span className="eyebrow">NOW · {fa?'همه آرام':'ALL QUIET'}</span><h1>{fa?'همه‌چیز آرام است':'You\'re all caught up'}</h1><p>{fa?'هیچ سفارش فعالی نداری؛ کشف بعدی همین پایین منتظر توست.':'No active missions right now. Your next discovery is waiting below.'}</p><button onClick={p.onExplore}>Continue exploring →</button></div>;if(p.scenario!=='active')return <div className="v1-now alert"><span className="eyebrow">{p.t.actionRequired}</span><h1>{p.scenario==='failed'?p.t.failedTitle:p.t.verifyTitle}</h1><p>{p.scenario==='failed'?p.t.failedSub:p.t.verifySub}</p><button onClick={p.onFix}>{p.scenario==='failed'?p.t.fixPayment:p.t.verifyCta||'Verify now'}</button></div>;return <div className="v1-now cinematic"><div><span className="eyebrow">{p.t.nowTag}</span><h1>{p.t.orderMoving}</h1><div className="v1-product"><b>{p.t.orderProduct}</b><small>#PT-10492 · {p.t.orderStatus}</small></div><button onClick={p.onToggleOrder}>{p.orderOpen?p.t.closeOrder:p.t.viewOrder} →</button>{p.orderOpen&&<div className="v1-meta"><span>Payment · {p.t.payVia}</span><span>ETA · {p.t.eta}</span><span>Progress · 67%</span></div>}</div><div className="v1-core"><strong>67%</strong><span>{p.t.stageDelivery}</span></div></div>}
export function WalletCard(p:any){return <div className="v1-wallet"><span className="eyebrow">{p.t.walletTag}</span><strong>{p.cur==='USD'?'$'+p.balance.toFixed(2):Math.round(p.balance*98500).toLocaleString()}</strong><small>{p.t.balanceSub}</small><div className="v1-seg"><button className={p.cur==='USD'?'on':''} onClick={()=>p.onCur('USD')}>USD</button><button className={p.cur==='IRT'?'on':''} onClick={()=>p.onCur('IRT')}>IRT</button></div><div className="v1-btns"><button onClick={p.onAdd}>＋ {p.t.addFunds}</button><button onClick={p.onWithdraw}>↙ {p.t.withdraw}</button></div></div>}
export function QuickActions(p:any){const a=[[p.t.addFunds,'＋',p.onAdd],[p.t.withdraw,'↙',p.onWithdraw],[p.t.qaOrders,'☷',p.onOrders]];return <div className="v1-qa">{a.map(([l,i,fn])=><button key={String(l)} onClick={fn}><span>{i}</span><b>{l}</b><small>{String(l)===p.t.addFunds?p.t.qaAddSub:String(l)===p.t.withdraw?p.t.qaWithdrawSub:p.t.qaOrdersSub}</small><em>→</em></button>)}</div>}
export function YourWorld(p:any){return <section><div className="v1-section-title">{p.t.worldTitle}</div><div className="v1-world">{[['RECENTLY VIEWED','Steam Wallet · $20'],['SAVED',`${p.saved.length} saved items`],['CONTINUE','Spotify Premium · 80%']].map(([h,b],i)=><div key={h}><small>{h}</small><b>{b}</b><button onClick={p.onContinue}>Open →</button></div>)}</div></section>}
export function Discovery(p:any){const s=(p.q||'').toLowerCase();const list=products.filter(x=>(x[0]+' '+x[1]).toLowerCase().includes(s));return <section id="discSec"><div className="v1-section-title">{p.t.discoverTitle}</div><div className="v1-products">{list.map((x,i)=><motion.button key={x[0]} whileHover={{y:-6}} onClick={p.onView}><div className={'art tone'+i}><span>{i===0?'TRENDING':i===1?'POPULAR':'FOR YOU'}</span></div><b>{p.lang==='fa'?x[1]:x[0]}</b><small>{x[2]}</small></motion.button>)}</div></section>}
export function Journey(p:{t:any;lang:Lang;journey:JourneyItem[]}){return <section><div className="v1-section-title">{p.t.journeyTitle}</div><div className="v1-journey">{p.journey.map((j,i)=><div key={i}><i className="dot"/><div><b>{p.t[j.k]}</b><small>{j.time[p.lang]}{j.amt?' · '+j.amt:''}</small></div></div>)}</div></section>}
export function Support(p:any){return <section id="supportSec" className="v1-support"><div><span className="eyebrow">{p.t.helpTitle}</span><h2>{p.t.helpSub}</h2></div><button onClick={p.onNewTicket}>＋ {p.t.newTicket}</button><button onClick={p.onHelp}>{p.t.helpCenter} →</button><small>{p.t.openTickets(p.tickets.length)}</small></section>}
export function Toast({msg}:{msg:string|null}){return msg?<div className="v1-toast">{msg}</div>:null}
export function AddFundsModal(p:any){return <AnimatePresence>{<motion.div className="v1-modal" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={p.onClose}><motion.div className="v1-dialog" onClick={e=>e.stopPropagation()}><h3>{p.t.modalAddTitle}</h3><p>{p.t.modalAddSub}</p><div className="v1-amounts">{[10,20,50,100].map(a=><button className={p.amt===a?'on':''} onClick={()=>p.setAmt(a)} key={a}>${a}</button>)}</div><button onClick={p.onConfirm}>{p.t.confirm}</button><button onClick={p.onClose}>{p.t.cancel}</button></motion.div></motion.div>}</AnimatePresence>}
export function TicketModal(p:any){return <AnimatePresence>{<motion.div className="v1-modal" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={p.onClose}><motion.div className="v1-dialog" onClick={e=>e.stopPropagation()}><h3>{p.t.modalTicketTitle}</h3><input placeholder={p.t.subjectPh}/><textarea placeholder={p.t.msgPh}/><button onClick={p.onSubmit}>{p.t.submit}</button><button onClick={p.onClose}>{p.t.cancel}</button></motion.div></motion.div>}</AnimatePresence>}
