import React,{useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import'./styles.css';

type Page='overview'|'users'|'sellers'|'requests'|'listings'|'orders'|'wallet'|'payouts'|'verification'|'disputes'|'risk'|'support'|'admins'|'audit'|'settings';
type Lang='fa'|'en';
const nav:[string,string,Page,string,string][]=[
['نمای کلی','Overview','overview','⌂','CONTROL'],['کاربران','Users','users','◉','MARKET'],['فروشندگان','Sellers','sellers','◈','MARKET'],['درخواست فروشندگی','Seller Requests','requests','↗','MARKET'],['آگهی‌ها','Listings','listings','▦','MARKET'],['سفارش‌ها و معاملات','Orders & Trades','orders','□','TRANSACTIONS'],['کیف پول پلتفرم','Platform Wallet','wallet','◒','FINANCE'],['برداشت‌ها','Payouts','payouts','$','FINANCE'],['احراز هویت','Verification / KYC','verification','✓','TRUST'],['اختلاف و بازگشت وجه','Disputes & Refunds','disputes','↺','TRUST'],['ریسک و اعتماد','Risk & Trust','risk','⚡','TRUST'],['پشتیبانی و تیکت‌ها','Support & Tickets','support','?','SUPPORT'],['ادمین‌ها و دسترسی','Admins & Roles','admins','⚙','SYSTEM'],['ثبت رویداد','Audit Log','audit','≋','SYSTEM'],['تنظیمات سیستم','System Settings','settings','◌','SYSTEM']];
const queue=[['درخواست فروشندگی','Seller applications','17','requests','cyan'],['آگهی منتظر تأیید','Listings awaiting review','9','listings','violet'],['معامله منتظر تأیید','Trades awaiting approval','6','orders','amber'],['برداشت منتظر بررسی','Payouts awaiting review','11','payouts','mint'],['احراز هویت','Verification cases','4','verification','rose']];
const notices=[['12:41','آگهی جدید ثبت شد','NightFox'],['12:38','درخواست برداشت','84.50$'],['12:34','بروزرسانی احراز هویت','Mina K'],['12:29','معامله آماده تأیید','PT-10492']];
const fa=(l:Lang,e:string,f:string)=>l==='fa'?f:e;

function BackgroundCore(){return <div className="bg-core" aria-hidden="true"><div className="core-a"/><div className="core-b"/><div className="core-c"/><div className="core-plane p1"/><div className="core-plane p2"/><div className="core-plane p3"/><div className="core-glint"/></div>}
function App(){const[page,setPage]=useState<Page>('overview');const[lang,setLang]=useState<Lang>('fa');const[dark,setDark]=useState(false);const[collapsed,setCollapsed]=useState(false);const[open,setOpen]=useState<string|null>(null);const groups=useMemo(()=>Array.from(new Set(nav.map(x=>x[4]))),[]);const faMode=lang==='fa';return <div className={`app ${dark?'dark':''} ${collapsed?'collapsed':''}`}>
{page==='overview'&&<BackgroundCore/>}
<aside className="sidebar glass">
<button className="sidebar-toggle" onClick={()=>setCollapsed(v=>!v)}>{collapsed?'›':'‹'}</button>
<div className="brand"><span className="brand-mark">P</span>{!collapsed&&<span><strong>PooriTel</strong><small>{faMode?'کنترل مدیریت':'ADMIN CONTROL'}</small></span>}</div>
<div className="nav-scroll">{groups.map(g=><section key={g}><div className="nav-group">{faMode?({CONTROL:'کنترل',MARKET:'بازار',TRANSACTIONS:'معاملات',FINANCE:'مالی',TRUST:'اعتماد',SUPPORT:'پشتیبانی',SYSTEM:'سیستم'} as any)[g]:g}</div>{nav.filter(x=>x[4]===g).map(x=><button key={x[2]} className={`nav-item ${page===x[2]?'active':''}`} onClick={()=>setPage(x[2])}><i>{x[3]}</i>{!collapsed&&<span>{faMode?x[0]:x[1]}</span>}{!collapsed&&['requests','listings','orders','payouts','verification','support'].includes(x[2])&&<b>{x[2]==='requests'?'17':x[2]==='listings'?'9':x[2]==='orders'?'6':x[2]==='payouts'?'11':x[2]==='verification'?'4':'5'}</b>}</button>)}</section>)}</div>
{!collapsed&&<div className="admin-foot"><div className="online"><span/> {fa(lang,'System healthy','سیستم پایدار')}</div><div className="admin-user"><span>P</span><div><strong>Pouria</strong><small>{fa(lang,'Super Admin','مدیر ارشد')}</small></div></div></div>}
</aside>
<main className="main">
<header className="topbar glass"><div className="mobile-brand"><span className="brand-mark">P</span></div><div className="crumb"><span>{fa(lang,'POORITEL ADMIN','ادمین پُری‌تل')}</span><b>/</b><strong>{faMode?(nav.find(x=>x[2]===page)?.[0]||'نمای کلی'):(nav.find(x=>x[2]===page)?.[1]||'Overview')}</strong></div><div className="top-actions"><button className="top-btn" onClick={()=>setLang(faMode?'en':'fa')}>{faMode?'EN':'فا'}</button><button className="top-btn" onClick={()=>setDark(v=>!v)}>{dark?'☀':'◐'}</button><button className="store-btn">{faMode?'فروشگاه ↗':'Open Store ↗'}</button></div></header>
<div className="content">{page==='overview'?<Overview faMode={faMode} open={setOpen}/>:<ListPage faMode={faMode} page={page} open={setOpen}/>}</div>
</main>
{open&&<Modal faMode={faMode} kind={open} close={()=>setOpen(null)}/>}</div>}

function Overview({faMode,open}:{faMode:boolean;open:(x:string)=>void}){return <div className="overview"><section className="overview-header"><div><span className="eyebrow">{faMode?'نمای کلی':'OVERVIEW'}</span><h1>{faMode?'مرکز کنترل':'Control Center'}</h1></div><div className="date-pill">{faMode?'امروز':'Today'} · 27 Aug 2026</div></section><section className="kpi-row"><Metric title={faMode?'حجم معاملات امروز':'GMV today'} value="$12,840" delta="+18.4%"/><Metric title={faMode?'سفارش‌های باز':'Open orders'} value="24" delta={faMode?'7 نیازمند اقدام':'7 need action'}/><Metric title={faMode?'کمیسیون این ماه':'Commission this month'} value="$8,240" delta="+9.6%"/><Metric title={faMode?'موجودی پلتفرم':'Platform balance'} value="$28,420" delta={faMode?'قابل تسویه':'Available'}/></section><section className="workspace"><div className="focus-panel glass"><div className="focus-copy"><span className="eyebrow">{faMode?'نیازمند اقدام':'ACTION QUEUE'}</span><h2>{faMode?'صف تصمیم‌ها':'Decision queue'}</h2><p>{faMode?'مواردی که بدون تصمیم ادمین جلو نمی‌روند.':'Items that cannot progress without an admin decision.'}</p></div><div className="queue">{queue.map(q=><button key={q[3]} className={`queue-row ${q[4]}`} onClick={()=>open(q[3])}><span className="q-count">{q[2]}</span><span className="q-copy"><strong>{faMode?q[0]:q[1]}</strong><small>{faMode?'برای بررسی آماده است':'Ready for review'}</small></span><em>→</em></button>)}</div></div><div className="right-stack"><div className="wallet-panel glass"><div className="panel-title"><span className="eyebrow">{faMode?'کیف پول پلتفرم':'PLATFORM WALLET'}</span><span className="live-dot"/></div><div className="wallet-number">$28,420</div><div className="wallet-grid"><span>{faMode?'کمیسیون':'Commission'}<b>$8,240</b></span><span>{faMode?'در انتظار تسویه':'Pending'}<b>$11,320</b></span><span>{faMode?'ذخیره بازگشت':'Reserve'}<b>$1,120</b></span></div></div><div className="activity-panel glass"><div className="panel-title"><span className="eyebrow">{faMode?'فعالیت':'LIVE ACTIVITY'}</span></div>{notices.map(n=><div className="activity" key={n[0]}><time>{n[0]}</time><strong>{n[1]}</strong><span>{n[2]}</span></div>)}</div></div></section><section className="health-panel glass"><div><span className="eyebrow">{faMode?'اعتماد و سلامت':'TRUST & HEALTH'}</span><h3>{faMode?'وضعیت بازار':'Marketplace state'}</h3></div><div className="health-items"><span><i className="ok"/> {faMode?'پرداخت سالم':'Payments healthy'}</span><span><i className="warn"/> {faMode?'4 احراز در انتظار':'4 KYC waiting'}</span><span><i className="warn"/> {faMode?'11 برداشت در انتظار':'11 payouts waiting'}</span><span><i className="ok"/> {faMode?'ریسک پایین':'Low risk'}</span></div></section></div>}
function Metric({title,value,delta}:{title:string;value:string;delta:string}){return <div className="metric glass"><span>{title}</span><strong>{value}</strong><small>{delta}</small><i/></div>}
function ListPage({faMode,page,open}:{faMode:boolean;page:Page;open:(x:string)=>void}){const labels:Record<Page,[string,string]>={overview:['',''],users:['کاربران','Users'],sellers:['فروشندگان','Sellers'],requests:['درخواست فروشندگی','Seller Requests'],listings:['آگهی‌ها','Listings'],orders:['سفارش‌ها و معاملات','Orders & Trades'],wallet:['کیف پول پلتفرم','Platform Wallet'],payouts:['برداشت‌ها','Payouts'],verification:['احراز هویت','Verification / KYC'],disputes:['اختلاف و بازگشت وجه','Disputes & Refunds'],risk:['ریسک و اعتماد','Risk & Trust'],support:['پشتیبانی و تیکت‌ها','Support & Tickets'],admins:['ادمین‌ها و دسترسی','Admins & Roles'],audit:['ثبت رویداد','Audit Log'],settings:['تنظیمات سیستم','System Settings']};const title=faMode?labels[page][0]:labels[page][1];const cards=page==='requests'?['NightFox','Ariya Games','Mina K','DotaKing']:page==='listings'?['Steam Wallet $20','Telegram Premium 3M','CS2 DreamHollow','Dota 2 Collector Set']:page==='verification'?['Mina K','DotaKing','NightFox']:['PT-10492','PT-10489','PT-10481','PT-10477'];return <div className="list-page"><div className="list-head"><div><span className="eyebrow">{faMode?'مدیریت':'MANAGEMENT'}</span><h1>{title}</h1></div><button className="primary">{faMode?'فیلترها':'Filters'}</button></div><div className="decision-list">{cards.map((c,i)=><button className="data-card glass" key={c} onClick={()=>open(page)}><div className="data-index">0{i+1}</div><div className="data-main"><strong>{c}</strong><span>{faMode?'اطلاعات آماده بررسی':'Review context available'}</span></div><div className="data-meta"><span>{faMode?'ریسک':'Risk'} <b>{i===2?'Medium':'Low'}</b></span><span>{faMode?'وضعیت':'Status'} <b>{faMode?'در انتظار':'Pending'}</b></span></div><em>→</em></button>)}</div></div>}
function Modal({faMode,kind,close}:{faMode:boolean;kind:string;close:()=>void}){const map:Record<string,[string,string]>= {requests:['درخواست فروشندگی','Seller application'],listings:['آگهی جدید','Listing review'],orders:['تأیید معامله','Trade approval'],payouts:['بررسی برداشت','Payout review'],verification:['بررسی احراز هویت','Verification review'],users:['کاربر','User review'],sellers:['فروشنده','Seller review'],wallet:['کیف پول پلتفرم','Platform wallet'],disputes:['اختلاف و بازگشت وجه','Dispute review'],risk:['ریسک و اعتماد','Risk review'],support:['تیکت پشتیبانی','Support ticket'],admins:['ادمین و دسترسی','Admin access'],audit:['ثبت رویداد','Audit event'],settings:['تنظیمات سیستم','System setting']};const t=faMode?map[kind]?.[0]||'جزئیات بررسی':map[kind]?.[1]||'Review details';return <div className="modal-backdrop" onMouseDown={close}><div className="modal-card glass" onMouseDown={e=>e.stopPropagation()}><button className="modal-close" onClick={close}>×</button><span className="eyebrow">{faMode?'فضای تصمیم':'DECISION WORKSPACE'}</span><h2>{t}</h2><div className="evidence-grid"><div><small>{faMode?'حساب':'ACCOUNT'}</small><b>NightFox</b></div><div><small>{faMode?'مبلغ':'AMOUNT'}</small><b>$84.50</b></div><div><small>{faMode?'ریسک':'RISK'}</small><b>LOW</b></div><div><small>{faMode?'مدرک':'EVIDENCE'}</small><b>{faMode?'آماده':'Ready'}</b></div></div><div className="preview-box"><div className="preview-art"/><div><span className="eyebrow">{faMode?'پیش‌نمایش':'PREVIEW'}</span><h3>{faMode?'موردی که در حال بررسی است':'Item under review'}</h3><p>{faMode?'اطلاعات کلیدی و شواهد در همین پنجره جمع شده‌اند.':'Key information and evidence are gathered here.'}</p></div></div><div className="modal-actions"><button>{faMode?'نگه‌داشتن':'Hold'}</button><button className="danger">{faMode?'رد':'Reject'}</button><button className="primary">{faMode?'تأیید':'Approve'} ✓</button></div></div></div>}

createRoot(document.getElementById('root')!).render(<App/>);
