import React,{useState} from 'react';import{createRoot}from'react-dom/client';import{LayoutDashboard,WalletCards,ShoppingBag,UserRound,ShieldCheck,Settings,Bell,ChevronRight,ChevronLeft,ArrowUpRight,Plus,Minus,Clock3,Sparkles,Menu}from'lucide-react';import'./style.css';
const orders=[{id:'PT-10492',name:'Telegram Premium · 12 months',amount:'$21.90',status:'در حال بررسی'},{id:'PT-10471',name:'Steam Wallet · 20 USD',amount:'$20.45',status:'تکمیل شده'},{id:'PT-10466',name:'Dota 2 Item Bundle',amount:'$15.00',status:'تکمیل شده'}];
function App(){const[open,setOpen]=useState(true);const[usd,setUsd]=useState(true);return <div className={'app '+(open?'open':'closed')}>
<aside className="side"><div className="brand"><div className="brandmark">P</div><div><b>PooriTel</b><span>Customer Space</span></div></div><button className="collapse" onClick={()=>setOpen(!open)}>{open?<ChevronRight/>:<ChevronLeft/>}</button><nav><a className="active"><LayoutDashboard/><span>نمای کلی</span></a><a><WalletCards/><span>کیف پول</span></a><a><ShoppingBag/><span>سفارش‌ها</span></a><div className="label">حساب</div><a><UserRound/><span>پروفایل</span></a><a><ShieldCheck/><span>امنیت و احراز</span></a><a><Settings/><span>تنظیمات</span></a></nav><div className="user-mini"><div className="avatar">P</div><div className="user-copy"><b>Pouria</b><span>customer@example.com</span></div></div></aside>
<main><header><div className="welcome"><div className="eyebrow"><Sparkles/> فضای شخصی شما</div><h1>سلام پوریا، آماده‌ای؟</h1><p>مهم‌ترین چیزها را همین‌جا می‌بینی.</p></div><div className="header-actions"><button><Bell/></button><button className="profile-dot">P</button></div></header>
<section className="hero"><div className="orb orb1"/><div className="orb orb2"/><div className="scan"/><div className="hero-copy"><span className="kicker">AVAILABLE BALANCE</span><div className="balance-row"><strong>{usd?'$124.50':'۱۲٬۴۵۰٬۰۰۰'}</strong><div className="currency-switch"><button className={usd?'on':''} onClick={()=>setUsd(true)}>USD</button><button className={!usd?'on':''} onClick={()=>setUsd(false)}>IRT</button></div></div><p>موجودی قابل استفاده</p><div className="hero-actions"><button className="primary"><Plus/> شارژ کیف پول</button><button className="ghost"><ArrowUpRight/> برداشت</button></div></div><div className="hero-visual"><div className="ring r1"/><div className="ring r2"/><div className="core"><Sparkles/></div><div className="floating f1">LIVE</div><div className="floating f2">SECURE</div></div></section>
<section className="quick"><div className="section-title"><span>دسترسی سریع</span><small>۳ عملیات اصلی</small></div><div className="quick-grid"><button className="qcard q1"><div className="qicon"><Plus/></div><div><b>شارژ کیف پول</b><span>افزایش موجودی</span></div><ArrowUpRight/></button><button className="qcard q2"><div className="qicon"><Minus/></div><div><b>برداشت</b><span>درخواست برداشت</span></div><ArrowUpRight/></button><button className="qcard q3"><div className="qicon"><ShoppingBag/></div><div><b>سفارش‌های من</b><span>۳ سفارش اخیر</span></div><ArrowUpRight/></button></div></section>
<section className="grid"><div className="panel orders"><div className="panel-head"><div><span className="eyebrow"><Clock3/> LATEST</span><h2>آخرین سفارش‌ها</h2></div><button className="text-btn">همه سفارش‌ها <ArrowUpRight/></button></div>{orders.map(o=><div className="order" key={o.id}><div className="product-icon"><ShoppingBag/></div><div className="od"><b>{o.name}</b><span>#{o.id}</span></div><div className="oa"><b>{o.amount}</b><span className={o.status==='تکمیل شده'?'done':'pending'}>{o.status}</span></div></div>)}</div><div className="panel health"><div className="panel-head"><div><span className="eyebrow"><ShieldCheck/> ACCOUNT</span><h2>وضعیت حساب</h2></div></div><div className="health-ring"><div><strong>92</strong><span>امنیت</span></div></div><div className="health-list"><div><span className="ok"/>ایمیل تأیید شده</div><div><span className="ok"/>حساب فعال</div><div><span className="ok"/>Session امن</div><div><span className="warn"/>احراز هویت ناقص</div></div></div></section>
<footer><span>آخرین به‌روزرسانی · همین الان</span><span>Customer Dashboard · Preview</span></footer></main></div>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);